/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */
module DIG_JK_FF
#(
    parameter Default = 1'b0
)
(
   input J,
   input C,
   input K,
   output Q,
   output \~Q
);
    reg state;

    assign Q = state;
    assign \~Q = ~state;

    always @ (posedge C) begin
        if (~J & K)
            state <= 1'b0;
         else if (J & ~K)
            state <= 1'b1;
         else if (J & K)
            state <= ~state;
    end

    initial begin
        state = Default;
    end
endmodule


module shf2 (
  input CLK,
  input SR,
  input SL,
  input IN_SR,
  input IN_SL,
  input [7:0] IN,
  input LD,
  output O_sr,
  output O_sl,
  output [7:0] O
);
  wire s0;
  wire s1;
  wire O_sl_temp;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  wire s6;
  wire s7;
  wire s8;
  wire s9;
  wire s10;
  wire s11;
  wire O_sr_temp;
  wire s12;
  wire s13;
  wire s14;
  wire s15;
  wire s16;
  wire s17;
  wire s18;
  wire s19;
  wire s20;
  wire s21;
  assign s1 = ((IN_SR & SR) | (IN[7] & LD) | (SL & s0));
  assign s3 = ((O_sl_temp & SR) | (IN[6] & LD) | (SL & s2));
  assign s5 = ((s0 & SR) | (IN[5] & LD) | (SL & s4));
  assign s7 = ((s2 & SR) | (IN[4] & LD) | (SL & s6));
  assign s9 = ((s4 & SR) | (IN[3] & LD) | (SL & s8));
  assign s11 = ((s6 & SR) | (IN[2] & LD) | (SL & s10));
  assign s12 = ((s8 & SR) | (IN[1] & LD) | (SL & O_sr_temp));
  assign s13 = ((s10 & SR) | (IN[0] & LD) | (SL & IN_SL));
  assign s14 = ~ s1;
  assign s15 = ~ s3;
  assign s16 = ~ s5;
  assign s17 = ~ s7;
  assign s18 = ~ s9;
  assign s19 = ~ s11;
  assign s20 = ~ s12;
  assign s21 = ~ s13;
  DIG_JK_FF #(
    .Default(0)
  )
  DIG_JK_FF_i0 (
    .J( s1 ),
    .C( CLK ),
    .K( s14 ),
    .Q( O_sl_temp )
  );
  DIG_JK_FF #(
    .Default(0)
  )
  DIG_JK_FF_i1 (
    .J( s3 ),
    .C( CLK ),
    .K( s15 ),
    .Q( s0 )
  );
  DIG_JK_FF #(
    .Default(0)
  )
  DIG_JK_FF_i2 (
    .J( s5 ),
    .C( CLK ),
    .K( s16 ),
    .Q( s2 )
  );
  DIG_JK_FF #(
    .Default(0)
  )
  DIG_JK_FF_i3 (
    .J( s7 ),
    .C( CLK ),
    .K( s17 ),
    .Q( s4 )
  );
  DIG_JK_FF #(
    .Default(0)
  )
  DIG_JK_FF_i4 (
    .J( s9 ),
    .C( CLK ),
    .K( s18 ),
    .Q( s6 )
  );
  DIG_JK_FF #(
    .Default(0)
  )
  DIG_JK_FF_i5 (
    .J( s11 ),
    .C( CLK ),
    .K( s19 ),
    .Q( s8 )
  );
  DIG_JK_FF #(
    .Default(0)
  )
  DIG_JK_FF_i6 (
    .J( s12 ),
    .C( CLK ),
    .K( s20 ),
    .Q( s10 )
  );
  DIG_JK_FF #(
    .Default(0)
  )
  DIG_JK_FF_i7 (
    .J( s13 ),
    .C( CLK ),
    .K( s21 ),
    .Q( O_sr_temp )
  );
  assign O[0] = O_sr_temp;
  assign O[1] = s10;
  assign O[2] = s8;
  assign O[3] = s6;
  assign O[4] = s4;
  assign O[5] = s2;
  assign O[6] = s0;
  assign O[7] = O_sl_temp;
  assign O_sr = O_sr_temp;
  assign O_sl = O_sl_temp;
endmodule
